version: '3.3'

services:
    #service 1: definition of drones
  drones:
    image: drones:3-management-alpine
    container_name: 'drones'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/drones/data/:/var/lib/drones/
        - ~/.docker-conf/drones/log/:/var/log/drones
    networks:
        - drones_go_net
    #service 3: definition of your spring-boot app 
    orderservice:                        #it is just a name, which will be used only in this file.
      image: drones-service               #name of the image after dockerfile executes
      container_name: drones-service-app  #name of the container created from docker image
      build:
        context: .                          #docker file path (. means root directory)
        dockerfile: Dockerfile              #docker file name
      ports:
        - "8081:8080"                       #docker containter port with your os port
      restart: always
      environment:
        - SPRING_DRONES_HOST=drones  
      depends_on:                           #define dependencies of this app
        - drones      
        